import Hero from '@/component/Hero'
import Instagram from '@/component/Instagram'
import Slider from '@/component/Slider'
import Head from 'next/head'
import {SliderData} from  '../component/Sliderdata'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Pixify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Hero heading="Capture photography" message="I capture moments and keep them alive" />
     
      <Slider slides={SliderData}/>
      <Instagram/>
    </div>
  )
}
